# Generated by Django 3.2.16 on 2022-11-20 20:55

from django.db import migrations, models
import email_user.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='email',
            field=email_user.fields.CaseEmailField(error_messages={'unique': 'A user with that email is already registered.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
